### ISSUE TITLE
[Bug] & [Request] Aicraft config documentation

### ISSUE THREAD

**Issue by Godehardt2003** [Sequal32/yourcontrols#176]
Hi,
my idea was to make a config yaml for the Hype H145. The problem there is that LVARs are not editable and the only way to change a value is to send an H event.
It worked already for a bool switch:
```
type: ToggleSwitch
    var_name: L:H145_SDK_OH_AVIONICS_1
    var_units: Bool
    var_type: bool
    event_name: H:H145_SDK_OH_AVIONICS_1_TOGGLE
    use_calculator: true
    cancel_h_events: true
```
It gets more complicated if there is a three position switch I tried the following:
```
type: NumSet
    var_name: L:H145_SDK_OH_LAVCS_SYSTEM
    var_type: f64
    event_name: H:H145_SDK_OH_LAVCS_OFF
    use_calculator: true
    cancel_h_events: true
    condition:
      equals:
        F64: 0.0
```
So if the LVAR is 0.0 it should send the OFF event... But this doesn't work and I don't know why. I tested the H events with a different program and everything worked fine so the H event is not broken.

Generally there is now way to understand the parameters exactly. No clue what "use_calculator" or "cancel_h_events" means. It was simply luck and help from Tailhook. Would be nice to get there a documentation. I could write one but without support and understanding it myself there is no way to do that...
